name: Lint

on: 
  push:
    branches-ignore: ['*dev*']
  pull_request:
    branches-ignore: ['*dev*']


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "-t py38 -t py39 -t py310 -t py311"
          src: "./envedit"
          jupyter: true
          version: "21.5b1"