name: Lint

on: 
  push:
    branches-ignore: ['*dev*']
  pull_request:
    branches-ignore: ['*dev*']


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable