name: Unit tests
run-name: ${{ github.actor }} is running unit tests
on: [push]
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: run test scripts
        run: |
           sh ${{ github.workspace }}/run_tests.sh
